# Generated by Django 3.2.7 on 2021-12-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=359, max_length=6),
        ),
    ]
