# Generated by Django 3.2.7 on 2021-12-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211229_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_submember',
            new_name='is_society_admin',
        ),
    ]
