# Generated by Django 3.2.7 on 2021-12-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_is_submember_user_is_society_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_society_admin',
        ),
    ]
