# Generated by Django 2.2.4 on 2021-12-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_auto_20211130_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_society_deatils',
            name='otp',
        ),
    ]
