# Generated by Django 3.2.7 on 2021-12-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_user_society_deatils_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
