# Generated by Django 3.2.7 on 2021-12-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_society_deatils',
            old_name='state',
            new_name='state1',
        ),
    ]
