# Generated by Django 3.2.7 on 2021-12-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_rename_state_user_society_deatils_state1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_society_deatils',
            old_name='state1',
            new_name='state',
        ),
    ]
