# Generated by Django 3.2.7 on 2021-12-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='society',
            name='city',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='society',
            name='country',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='society',
            name='pincode',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='society',
            name='state',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
