# Generated by Django 3.2.7 on 2021-12-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_auto_20211211_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='registration_number',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
