# Generated by Django 3.2.7 on 2021-12-15 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0052_auto_20211215_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_society_deatils',
            name='is_verfied',
        ),
        migrations.RemoveField(
            model_name='user_society_deatils',
            name='password',
        ),
        migrations.AddField(
            model_name='user_society_deatils',
            name='user_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
