# Generated by Django 3.2.7 on 2021-12-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_societydeatils'),
    ]

    operations = [
        migrations.AddField(
            model_name='assentcategory',
            name='society_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.societydeatils'),
        ),
        migrations.AddField(
            model_name='balancevalue',
            name='society_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.societydeatils'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='society_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.societydeatils'),
        ),
        migrations.AddField(
            model_name='filestorevalue1',
            name='society_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.societydeatils'),
        ),
        migrations.AddField(
            model_name='income_expense_ledgervalue1',
            name='society_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.societydeatils'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='society_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.societydeatils'),
        ),
        migrations.AddField(
            model_name='members_vendor_account',
            name='society_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.societydeatils'),
        ),
        migrations.AddField(
            model_name='membersdeatilsvalue',
            name='society_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.societydeatils'),
        ),
    ]
