# Generated by Django 3.2.7 on 2021-12-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_auto_20211220_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Society',
        ),
    ]
