# Generated by Django 3.2.7 on 2021-12-20 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0057_delete_society'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_name', models.CharField(max_length=500)),
                ('society_name', models.CharField(max_length=500)),
                ('society_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=10)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('society_registration_number', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
