# Generated by Django 3.2.7 on 2021-12-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_auto_20211220_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_ledgervalue1',
            name='dateOn',
            field=models.DateField(auto_now=True),
        ),
    ]
