# Generated by Django 3.2.7 on 2021-12-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_alter_income_expense_ledgervalue1_dateon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_ledgervalue1',
            name='dateOn',
            field=models.DateField(),
        ),
    ]
