# Generated by Django 3.2.7 on 2021-12-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_alter_income_expense_ledgervalue1_dateon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancevalue',
            name='account',
            field=models.CharField(max_length=100),
        ),
    ]
