# Generated by Django 3.2.7 on 2021-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_auto_20211221_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='category_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='category_name',
            field=models.CharField(max_length=200),
        ),
    ]
