# Generated by Django 3.2.7 on 2021-12-25 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_auto_20211221_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='subUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('Type', models.CharField(blank=True, max_length=200, null=True)),
                ('access_rights', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('society_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.society')),
            ],
        ),
    ]
