# Generated by Django 3.2.7 on 2021-12-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_subuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssentCategory1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('society_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.society')),
            ],
        ),
    ]
