# Generated by Django 3.2.7 on 2021-12-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_asset_inventorycategoryvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_inventorycategoryvalue',
            name='deprecatedPrice',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset_inventorycategoryvalue',
            name='marketValue',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset_inventorycategoryvalue',
            name='purchasePrice',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset_inventorycategoryvalue',
            name='quantity',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset_inventorycategoryvalue',
            name='totalCost',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
