# Generated by Django 3.2.7 on 2021-12-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_auto_20211228_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset_InventoryCategory',
        ),
    ]
