# Generated by Django 3.2.7 on 2021-12-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_asset_inventorycategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset_InventoryCategory',
        ),
    ]
