# Generated by Django 3.2.7 on 2021-12-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_delete_asset_inventorycategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssentCategory',
        ),
    ]
