# Generated by Django 3.2.7 on 2021-12-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_delete_assentcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembersDeatils',
        ),
    ]
