# Generated by Django 3.2.7 on 2021-12-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_subuser1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser1',
            name='user_key',
        ),
        migrations.DeleteModel(
            name='Asset_InventoryCategoryValue',
        ),
    ]
