# Generated by Django 3.2.7 on 2021-12-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_alter_society_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subUser',
        ),
    ]
