# Generated by Django 3.2.7 on 2021-12-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_delete_subuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser1',
            name='is_society_admin',
            field=models.BooleanField(default=False),
        ),
    ]
