# Generated by Django 3.2.7 on 2021-12-30 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0081_subuser1_is_society_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubUser1',
            new_name='UserPermission',
        ),
    ]
